version: '3.8'

services:
  database:
    container_name: game_random_db
    image: postgres:13.6-alpine
    restart: always
    environment:
      TZ: 'Asia/Ho_Chi_Minh'
      PGTZ: 'Asia/Ho_Chi_Minh'
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - ./docker/database/postgres/data/:/var/lib/postgresql/datadocker
    env_file:
      - .env

  redis:
    container_name: game_random_redis
    image: 'redis:alpine'
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./docker/database/redis/data:/data

  app:
    container_name: game_random_be
    image: game_random_be
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    depends_on:
      - database
      - redis
